; PlatformIO Project Configuration File

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
test_framework = unity
monitor_speed = 115200

build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -Iinclude
    -DMY_WIFI_SSID=\"${sysenv.WIFI_SSID}\"
    -DMY_WIFI_PASSWORD=\"${sysenv.WIFI_PASSWORD}\"
    -DMY_LOGGER_HOST=\"${sysenv.LOGGER_HOST}\"
    -DMY_LOGGER_PORT=${sysenv.LOGGER_PORT}

lib_deps =
    pololu/VL53L0X
    robtillaart/AS5600

[env:native]
platform = native
test_framework = unity

build_flags =
    -std=c++17
    -Iinclude

